# Git PR Flow 配置文件
# 用于当前项目的 GPF 工作流配置

epic:
  epic_base_branch: "develop"

worktree:
  enabled: true
  worktree_dir: ".worktrees"
  worktree_epic_name: "epic--{epic-name}"
  worktree_epic_feature_name: "epic--{epic-name}--{feature-name}"

git:
  git_epic_branch: "epic/{epic-name}"
  git_epic_feature_branch: "{epic-name}/{feature-name}"